#!/usr/bin/env bash
#
# Deploy Chirp. Run as root on the VPS, from the repo checkout:
#
#     cd /srv/chirp && git pull && sudo ./deploy/deploy.sh
#
# Idempotent: safe to re-run. It never touches twitter.db or uploads/ (both are
# gitignored, so `git pull` leaves them alone too), and it preserves the
# SESSION_SECRET_KEY it generated on the first run.
set -euo pipefail

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m  %s\n' "$*" >&2; }
die()  { printf '\033[1;31mxx\033[0m  %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run as root (sudo ./deploy/deploy.sh)"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONF="$REPO_DIR/deploy/deploy.conf"
[[ -f "$CONF" ]] || die "missing $CONF -- copy deploy/deploy.conf.example and edit it"
# shellcheck source=/dev/null
source "$CONF"

: "${DOMAIN:?set DOMAIN in deploy.conf}"
: "${APP_DIR:?set APP_DIR in deploy.conf}"
: "${APP_USER:?set APP_USER in deploy.conf}"
: "${BIND_HOST:=127.0.0.1}"
: "${BIND_PORT:=8000}"
: "${REDIS_URL:=redis://127.0.0.1:6379/0}"
: "${REDIRECT_WWW:=true}"

BACKEND="$APP_DIR/backend"
FRONTEND="$APP_DIR/frontend"
DIST="$FRONTEND/dist"
ENV_FILE="$BACKEND/.env"
VENV="$BACKEND/.venv"
STAMP_DIR="$APP_DIR/.deploy"

# Note ${VAR:+...} would expand for the string "false" too, since it tests for
# non-empty rather than truthy. Compute the suffixes explicitly.
WWW_NAME=""
CERTBOT_WWW=""
if [[ "$REDIRECT_WWW" == true ]]; then
    WWW_NAME=" www.$DOMAIN"
    CERTBOT_WWW=" -d www.$DOMAIN"
fi

[[ "$REPO_DIR" == "$APP_DIR" ]] || warn "repo is at $REPO_DIR but APP_DIR=$APP_DIR; services will point at $APP_DIR"

# ---------------------------------------------------------------- packages
log "installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq nginx redis-server nodejs npm curl ca-certificates sqlite3

# Redis must never be reachable from the internet.
REDIS_CHANGED=false
if ! grep -qE '^bind 127\.0\.0\.1' /etc/redis/redis.conf; then
    log "binding redis to loopback"
    sed -i 's/^bind .*/bind 127.0.0.1 -::1/' /etc/redis/redis.conf
    REDIS_CHANGED=true
fi

# Sessions live in Redis. Without persistence, a redis restart logs everyone out.
if ! grep -qE '^appendonly yes' /etc/redis/redis.conf; then
    log "enabling redis AOF persistence (sessions survive a restart)"
    sed -i 's/^appendonly .*/appendonly yes/' /etc/redis/redis.conf
    grep -qE '^appendonly yes' /etc/redis/redis.conf || echo 'appendonly yes' >> /etc/redis/redis.conf
    REDIS_CHANGED=true
fi

if [[ "$REDIS_CHANGED" == true ]]; then
    systemctl restart redis-server
fi
systemctl enable --now redis-server >/dev/null

if ! command -v uv >/dev/null 2>&1; then
    log "installing uv"
    curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR=/usr/local/bin sh
fi
UV="$(command -v uv)"

# ---------------------------------------------------------------- user & perms
if ! id -u "$APP_USER" >/dev/null 2>&1; then
    log "creating system user $APP_USER"
    adduser --system --group --home "$APP_DIR" --no-create-home "$APP_USER"
fi

mkdir -p "$BACKEND/uploads"
chown -R "$APP_USER:$APP_USER" "$APP_DIR"
# nginx (www-data) must be able to traverse down to uploads/
chmod 755 "$APP_DIR" "$BACKEND"

# ---------------------------------------------------------------- app config
if [[ -f "$ENV_FILE" ]]; then
    log "keeping existing $ENV_FILE (session secret preserved)"
    SECRET="$(grep -E '^SESSION_SECRET_KEY=' "$ENV_FILE" | cut -d= -f2-)"
    [[ -n "$SECRET" ]] || die "$ENV_FILE has no SESSION_SECRET_KEY"
else
    log "generating $ENV_FILE with a fresh session secret"
    SECRET="$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')"
fi

cat >"$ENV_FILE" <<EOF
# Generated by deploy/deploy.sh -- edit deploy.conf, not this file.
DATABASE_URL=sqlite:///./twitter.db
REDIS_URL=$REDIS_URL
FRONTEND_ORIGIN=https://$DOMAIN

# Signs the opaque session id in the cookie. Rotating it invalidates every
# session at once; to drop a single session, delete its Redis key instead.
SESSION_SECRET_KEY=$SECRET

# Idle timeout. The TTL slides forward on each authenticated request.
SESSION_TTL_SECONDS=1209600

# The app refuses to boot if either of these is wrong for a public deploy.
SESSION_COOKIE_SECURE=true
DEV_ALLOW_HEADER_AUTH=false

RATE_LIMIT_ENABLED=true
DEV_AUTO_SYNC_SQLITE_SCHEMA=true

# Keeps the resolved-IP SSRF check on for link-preview fetches.
LINK_PREVIEW_VERIFY_DNS=true
EOF
chown "$APP_USER:$APP_USER" "$ENV_FILE"
chmod 600 "$ENV_FILE"

# ---------------------------------------------------------------- build
log "installing backend dependencies"
sudo -u "$APP_USER" env HOME="$APP_DIR" "$UV" sync --frozen --no-dev --project "$BACKEND"

mkdir -p "$STAMP_DIR"
chown "$APP_USER:$APP_USER" "$STAMP_DIR"

# Content fingerprint of everything the bundle is built from. node_modules and
# dist are excluded: one is an input we track via the lockfile, the other is the
# output. DOMAIN is folded in because it becomes VITE_API_BASE_URL inside the
# bundle, so changing the domain must force a rebuild.
frontend_fingerprint() {
    {
        printf 'domain=%s\n' "$DOMAIN"
        find "$FRONTEND" \
            -path "$FRONTEND/node_modules" -prune -o \
            -path "$FRONTEND/dist" -prune -o \
            -type f -print0 | sort -z | xargs -0 sha256sum
    } | sha256sum | cut -d' ' -f1
}

LOCK_FP="$(sha256sum "$FRONTEND/package.json" "$FRONTEND/package-lock.json" | sha256sum | cut -d' ' -f1)"
BUILD_FP="$(frontend_fingerprint)"
FORCE="${FORCE_BUILD:-0}"

# `npm ci` deletes node_modules and reinstalls from scratch every time (~15s).
# Only pay that when the lockfile actually moved.
if [[ "$FORCE" == 1 || ! -d "$FRONTEND/node_modules" ||
      "$LOCK_FP" != "$(cat "$STAMP_DIR/npm.stamp" 2>/dev/null || true)" ]]; then
    log "installing frontend dependencies"
    sudo -u "$APP_USER" env HOME="$APP_DIR" \
        sh -c "cd '$FRONTEND' && npm ci --no-audit --no-fund --prefer-offline"
    printf '%s' "$LOCK_FP" >"$STAMP_DIR/npm.stamp"
else
    log "frontend dependencies unchanged, skipping npm ci"
fi

if [[ "$FORCE" == 1 || ! -f "$DIST/index.html" ||
      "$BUILD_FP" != "$(cat "$STAMP_DIR/build.stamp" 2>/dev/null || true)" ]]; then
    log "building frontend"
    sudo -u "$APP_USER" env HOME="$APP_DIR" VITE_API_BASE_URL="https://$DOMAIN/api/v1" \
        sh -c "cd '$FRONTEND' && npm run build"
    printf '%s' "$BUILD_FP" >"$STAMP_DIR/build.stamp"
else
    log "frontend unchanged, skipping build (FORCE_BUILD=1 to override)"
fi

chown "$APP_USER:$APP_USER" "$STAMP_DIR"/*.stamp 2>/dev/null || true

if [[ ! -f "$BACKEND/twitter.db" ]]; then
    warn "no $BACKEND/twitter.db -- the app will create an empty one."
    warn "To keep the dev/test data, copy the pruned database over before starting:"
    warn "    scp deploy/out/twitter.db root@$DOMAIN:$BACKEND/twitter.db"
    warn "    scp -r deploy/out/uploads/ root@$DOMAIN:$BACKEND/"
fi

# ---------------------------------------------------------------- systemd
log "installing systemd units"

# --workers 1: the API and the RQ worker already share one SQLite file. More
#   workers add write contention, not throughput.
# --proxy-headers: without it request.client.host is nginx for every request,
#   so all anonymous callers would share one rate-limit bucket.
cat >/etc/systemd/system/chirp-api.service <<EOF
[Unit]
Description=Chirp API (FastAPI / uvicorn)
After=network-online.target redis-server.service
Wants=network-online.target
Requires=redis-server.service

[Service]
Type=exec
User=$APP_USER
Group=$APP_USER
WorkingDirectory=$BACKEND
EnvironmentFile=$ENV_FILE
ExecStart=$VENV/bin/uvicorn main:app --host $BIND_HOST --port $BIND_PORT --workers 1 --proxy-headers --forwarded-allow-ips=$BIND_HOST
Restart=on-failure
RestartSec=2
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$BACKEND

[Install]
WantedBy=multi-user.target
EOF

# Invoked as a module: pyproject.toml declares no [build-system], so uv never
# installs the project and no console script exists in .venv/bin.
cat >/etc/systemd/system/chirp-worker.service <<EOF
[Unit]
Description=Chirp RQ worker (timeline fan-out on write)
After=network-online.target redis-server.service
Wants=network-online.target
Requires=redis-server.service

[Service]
Type=exec
User=$APP_USER
Group=$APP_USER
WorkingDirectory=$BACKEND
EnvironmentFile=$ENV_FILE
ExecStart=$VENV/bin/python -m app.worker
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$BACKEND

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload

# ---------------------------------------------------------------- nginx
HAS_CERT=false
[[ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]] && HAS_CERT=true

log "writing nginx site (tls certs present: $HAS_CERT)"

SITE=/etc/nginx/sites-available/chirp
{
if [[ "$HAS_CERT" == true ]]; then
cat <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN$WWW_NAME;
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://$DOMAIN\$request_uri; }
}
EOF
if [[ "$REDIRECT_WWW" == true ]]; then
cat <<EOF

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name www.$DOMAIN;
    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    return 301 https://$DOMAIN\$request_uri;
}
EOF
fi
cat <<EOF

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name $DOMAIN;
    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
EOF
else
# No certs yet: serve plain HTTP so certbot --nginx can find the server block.
cat <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN$WWW_NAME;
EOF
fi

cat <<EOF

    root $DIST;
    index index.html;

    # media.py caps video uploads at 50 MB.
    client_max_body_size 60m;

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    location /api/ {
        proxy_pass http://$BIND_HOST:$BIND_PORT;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        # Empty value = nginx drops the header. Defence in depth: the app only
        # honours X-User-Id as auth when DEV_ALLOW_HEADER_AUTH is on.
        proxy_set_header X-User-Id "";
        # Link-preview unfurls make an outbound fetch before responding.
        proxy_read_timeout 30s;
    }

    # User-uploaded bytes: serve from disk, never execute or sniff.
    location /uploads/ {
        alias $BACKEND/uploads/;
        try_files \$uri =404;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, immutable";
        add_header X-Content-Type-Options nosniff always;
        add_header Content-Security-Policy "default-src 'none'; sandbox" always;
    }

    # Vite emits content-hashed filenames here.
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA fallback: React Router owns /tweet/123, /u/dev, ...
    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
EOF
} >"$SITE"

# Another enabled site claiming the same server_name would be silently ignored by
# nginx (first block wins, later duplicates get a "conflicting server name"
# warning) -- which means deploying Chirp could take a running site offline.
# Refuse rather than hijack.
shopt -s nullglob
for other in /etc/nginx/sites-enabled/*; do
    [[ "$(basename "$other")" == "chirp" ]] && continue
    if grep -qE "^\s*server_name\b[^;]*(\s|^)${DOMAIN//./\\.}(\s|;)" "$other"; then
        die "$(basename "$other") already serves '$DOMAIN'. Deploying here would take it
    offline. Pick a different DOMAIN in deploy/deploy.conf (e.g. chirp.$DOMAIN),
    or disable that site first: rm /etc/nginx/sites-enabled/$(basename "$other")"
    fi
done
shopt -u nullglob

ln -sfn "$SITE" /etc/nginx/sites-enabled/chirp
rm -f /etc/nginx/sites-enabled/default
nginx -t

# ---------------------------------------------------------------- start
# Re-assert ownership: the database and uploads are copied in out-of-band (often
# over scp as root), and the app cannot open a root-owned SQLite file for write.
chown -R "$APP_USER:$APP_USER" "$BACKEND"

# nginx (www-data) serves /uploads/ from disk. An scp -r can land the directory
# as 0700, which turns every avatar and image into a 403. a+rX adds read for
# everyone and traverse on directories, without marking files executable.
chmod -R a+rX "$BACKEND/uploads"

log "restarting services"
systemctl enable chirp-api chirp-worker >/dev/null
systemctl restart chirp-api chirp-worker
systemctl reload nginx

log "health check"
# Type=exec marks the unit active as soon as execve() succeeds, not when uvicorn
# is listening. Importing FastAPI + SQLAlchemy can take several seconds on a
# small VPS, so poll instead of sleeping a fixed amount.
code=000
for _ in $(seq 1 30); do
    if ! systemctl is-active --quiet chirp-api; then
        journalctl -u chirp-api -n 40 --no-pager >&2
        die "chirp-api died during startup"
    fi
    code="$(curl -s -o /dev/null -w '%{http_code}' "http://$BIND_HOST:$BIND_PORT/" || true)"
    [[ "$code" == "200" ]] && break
    sleep 1
done

if [[ "$code" != "200" ]]; then
    journalctl -u chirp-api -n 40 --no-pager >&2
    die "API did not answer on http://$BIND_HOST:$BIND_PORT/ after 30s (got $code)"
fi

systemctl is-active --quiet chirp-worker || {
    journalctl -u chirp-worker -n 30 --no-pager >&2
    die "chirp-worker failed to start"
}

# Surface the row count: a database clobbered by a stale WAL replay looks like a
# perfectly healthy empty site otherwise.
USER_COUNT="$(sudo -u "$APP_USER" sqlite3 "$BACKEND/twitter.db" \
    'SELECT COUNT(*) FROM users' 2>/dev/null || echo '?')"
log "database: $USER_COUNT users"
if [[ "$USER_COUNT" == "0" ]]; then
    warn "the database has no users. If you expected the pruned dev/test data,"
    warn "a stale twitter.db-wal probably overwrote it -- see deploy/README.md."
fi

# Must be 401: X-User-Id is not a credential.
code="$(curl -s -o /dev/null -w '%{http_code}' -H 'X-User-Id: 1' \
    "http://$BIND_HOST:$BIND_PORT/api/v1/auth/me" || true)"
[[ "$code" == "401" ]] || die "SECURITY: X-User-Id returned $code, expected 401"

log "deployed. https://$DOMAIN"
if [[ "$HAS_CERT" != true ]]; then
    warn "no TLS certificate yet -- the site is HTTP only and SESSION_COOKIE_SECURE=true"
    warn "means login cookies will NOT be stored by the browser. Run:"
    warn "    apt install -y certbot python3-certbot-nginx"
    warn "    certbot --nginx -d $DOMAIN$CERTBOT_WWW"
    warn "    ./deploy/deploy.sh    # re-run to switch the site to HTTPS"
fi
