"""add user suspension

``users.suspended_at``: a moderator freeze. The account keeps all its data --
unlike ``deleted_at``, which scrubs -- but login is refused, sessions are
revoked, and read paths hide the account exactly as they hide a deleted one.
Clearing the stamp restores everything, which is the point: a suspension is a
judgement a moderator must be able to reverse.

Revision ID: 0017
Revises: 0016
Create Date: 2026-07-19

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0017'
down_revision: Union[str, Sequence[str], None] = '0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('suspended_at')

    # ### end Alembic commands ###
