export interface EmojiItem {
  char: string;
  name: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys & people",
    icon: "😀",
    emojis: [
      { char: "😀", name: "grinning face smile happy" },
      { char: "😃", name: "smiley happy joy" },
      { char: "😄", name: "smile happy laugh" },
      { char: "😁", name: "grin beaming happy" },
      { char: "😆", name: "laughing satisfied happy" },
      { char: "😅", name: "sweat smile relief nervous" },
      { char: "😂", name: "joy tears laugh lol" },
      { char: "🤣", name: "rofl rolling laughing lol" },
      { char: "😊", name: "blush smile happy" },
      { char: "😇", name: "innocent angel halo" },
      { char: "🙂", name: "slight smile happy" },
      { char: "🙃", name: "upside down silly" },
      { char: "😉", name: "wink flirt" },
      { char: "😌", name: "relieved calm content" },
      { char: "😍", name: "heart eyes love crush" },
      { char: "🥰", name: "smiling hearts love adore" },
      { char: "😘", name: "kiss blow love" },
      { char: "😗", name: "kissing" },
      { char: "😙", name: "kissing smiling" },
      { char: "😚", name: "kissing closed eyes" },
      { char: "😋", name: "yum tasty delicious tongue" },
      { char: "😛", name: "tongue playful" },
      { char: "😝", name: "squint tongue playful" },
      { char: "😜", name: "wink tongue crazy" },
      { char: "🤪", name: "zany goofy crazy" },
      { char: "🤨", name: "raised eyebrow skeptical" },
      { char: "🧐", name: "monocle thinking inspect" },
      { char: "🤓", name: "nerd geek glasses" },
      { char: "😎", name: "cool sunglasses" },
      { char: "🥳", name: "party celebrate hat" },
      { char: "🤩", name: "star struck excited wow" },
      { char: "😏", name: "smirk sly" },
      { char: "😒", name: "unamused meh" },
      { char: "😞", name: "disappointed sad" },
      { char: "😔", name: "pensive sad" },
      { char: "😟", name: "worried sad" },
      { char: "😕", name: "confused" },
      { char: "🙁", name: "slight frown sad" },
      { char: "😣", name: "persevere struggle" },
      { char: "😖", name: "confounded" },
      { char: "😫", name: "tired weary" },
      { char: "😩", name: "weary tired" },
      { char: "🥺", name: "pleading puppy eyes beg" },
      { char: "😢", name: "cry sad tear" },
      { char: "😭", name: "sob crying loud sad" },
      { char: "😤", name: "triumph steam angry" },
      { char: "😠", name: "angry mad" },
      { char: "😡", name: "rage furious mad" },
      { char: "🤬", name: "swearing cursing angry" },
      { char: "🤯", name: "mind blown shocked" },
      { char: "😳", name: "flushed embarrassed" },
      { char: "🥵", name: "hot heat sweating" },
      { char: "🥶", name: "cold freezing" },
      { char: "😱", name: "scream fear shocked" },
      { char: "😨", name: "fearful scared" },
      { char: "😰", name: "anxious sweat nervous" },
      { char: "😥", name: "sad relieved disappointed" },
      { char: "😓", name: "downcast sweat tired" },
      { char: "🤗", name: "hug hugging" },
      { char: "🤔", name: "thinking hmm consider" },
      { char: "🤭", name: "hand over mouth giggle oops" },
      { char: "🤫", name: "shush quiet secret" },
      { char: "🤥", name: "lying liar nose" },
      { char: "😶", name: "no mouth speechless" },
      { char: "😐", name: "neutral meh" },
      { char: "😑", name: "expressionless blank" },
      { char: "😬", name: "grimace awkward" },
      { char: "🙄", name: "eye roll whatever" },
      { char: "😯", name: "hushed surprised" },
      { char: "😦", name: "frowning open mouth" },
      { char: "😧", name: "anguished" },
      { char: "😮", name: "open mouth wow surprised" },
      { char: "😲", name: "astonished shocked" },
      { char: "🥱", name: "yawn tired bored" },
      { char: "😴", name: "sleeping zzz tired" },
      { char: "🤤", name: "drooling" },
      { char: "😪", name: "sleepy tired" },
      { char: "😵", name: "dizzy knocked out" },
      { char: "🤐", name: "zipper mouth quiet" },
      { char: "🥴", name: "woozy drunk tipsy" },
      { char: "🤢", name: "nauseated sick gross" },
      { char: "🤮", name: "vomit sick throw up" },
      { char: "🤧", name: "sneeze sick tissue" },
      { char: "😷", name: "mask sick ill" },
      { char: "🤒", name: "thermometer sick fever" },
      { char: "🤕", name: "bandage hurt injured" },
      { char: "🤑", name: "money mouth rich" },
      { char: "🤠", name: "cowboy hat" },
      { char: "😈", name: "devil smiling imp mischief" },
      { char: "👿", name: "angry devil imp" },
      { char: "👹", name: "ogre monster" },
      { char: "👺", name: "goblin monster" },
      { char: "💀", name: "skull death dead" },
      { char: "👻", name: "ghost boo spooky" },
      { char: "👽", name: "alien ufo" },
      { char: "🤖", name: "robot bot" },
      { char: "💩", name: "poop pile funny" },
      { char: "👋", name: "wave hello hi bye hand" },
      { char: "🤚", name: "raised back hand" },
      { char: "🖐️", name: "hand fingers splayed" },
      { char: "✋", name: "raised hand stop high five" },
      { char: "👌", name: "ok hand perfect" },
      { char: "🤌", name: "pinched fingers italian" },
      { char: "🤏", name: "pinch small little" },
      { char: "✌️", name: "victory peace" },
      { char: "🤞", name: "fingers crossed luck hope" },
      { char: "🤟", name: "love you gesture" },
      { char: "🤘", name: "rock horns metal" },
      { char: "🤙", name: "call me shaka" },
      { char: "👈", name: "point left" },
      { char: "👉", name: "point right" },
      { char: "👆", name: "point up" },
      { char: "👇", name: "point down" },
      { char: "☝️", name: "index point up" },
      { char: "👍", name: "thumbs up like yes good" },
      { char: "👎", name: "thumbs down dislike no bad" },
      { char: "✊", name: "fist raised power" },
      { char: "👊", name: "fist bump punch" },
      { char: "🤛", name: "left fist bump" },
      { char: "🤜", name: "right fist bump" },
      { char: "👏", name: "clap applause bravo" },
      { char: "🙌", name: "raised hands celebrate praise" },
      { char: "👐", name: "open hands" },
      { char: "🤲", name: "palms up together pray" },
      { char: "🙏", name: "pray thanks please hope" },
      { char: "🤝", name: "handshake deal agreement" },
      { char: "💪", name: "muscle strong flex" },
      { char: "❤️", name: "red heart love" },
      { char: "🧡", name: "orange heart" },
      { char: "💛", name: "yellow heart" },
      { char: "💚", name: "green heart" },
      { char: "💙", name: "blue heart" },
      { char: "💜", name: "purple heart" },
      { char: "🖤", name: "black heart" },
      { char: "🤍", name: "white heart" },
      { char: "🤎", name: "brown heart" },
      { char: "💔", name: "broken heart" },
      { char: "❣️", name: "heart exclamation" },
      { char: "💕", name: "two hearts love" },
      { char: "💞", name: "revolving hearts" },
      { char: "💓", name: "beating heart" },
      { char: "💗", name: "growing heart" },
      { char: "💖", name: "sparkling heart" },
      { char: "💘", name: "heart arrow cupid" },
      { char: "💝", name: "heart gift ribbon" },
      { char: "💯", name: "hundred perfect score" },
      { char: "💢", name: "anger symbol" },
      { char: "💥", name: "boom collision explosion" },
      { char: "💫", name: "dizzy star" },
      { char: "💦", name: "sweat droplets water" },
      { char: "💨", name: "dash wind fast" },
      { char: "🔥", name: "fire lit hot flame" },
      { char: "✨", name: "sparkles shiny stars" },
      { char: "🎉", name: "party popper celebrate tada" },
      { char: "🎊", name: "confetti ball celebrate" },
    ],
  },
  {
    id: "animals",
    label: "Animals & nature",
    icon: "🐻",
    emojis: [
      { char: "🐶", name: "dog puppy" },
      { char: "🐱", name: "cat kitten" },
      { char: "🐭", name: "mouse" },
      { char: "🐹", name: "hamster" },
      { char: "🐰", name: "rabbit bunny" },
      { char: "🦊", name: "fox" },
      { char: "🐻", name: "bear" },
      { char: "🐼", name: "panda" },
      { char: "🐨", name: "koala" },
      { char: "🐯", name: "tiger" },
      { char: "🦁", name: "lion" },
      { char: "🐮", name: "cow" },
      { char: "🐷", name: "pig" },
      { char: "🐸", name: "frog" },
      { char: "🐵", name: "monkey" },
      { char: "🐔", name: "chicken" },
      { char: "🐧", name: "penguin" },
      { char: "🐦", name: "bird" },
      { char: "🐤", name: "baby chick" },
      { char: "🦆", name: "duck" },
      { char: "🦅", name: "eagle" },
      { char: "🦉", name: "owl" },
      { char: "🦇", name: "bat" },
      { char: "🐺", name: "wolf" },
      { char: "🐗", name: "boar" },
      { char: "🐴", name: "horse" },
      { char: "🦄", name: "unicorn" },
      { char: "🐝", name: "bee honeybee" },
      { char: "🐛", name: "bug caterpillar" },
      { char: "🦋", name: "butterfly" },
      { char: "🐌", name: "snail" },
      { char: "🐞", name: "ladybug" },
      { char: "🐢", name: "turtle" },
      { char: "🐍", name: "snake" },
      { char: "🐙", name: "octopus" },
      { char: "🦑", name: "squid" },
      { char: "🦐", name: "shrimp" },
      { char: "🦀", name: "crab" },
      { char: "🐠", name: "tropical fish" },
      { char: "🐟", name: "fish" },
      { char: "🐬", name: "dolphin" },
      { char: "🐳", name: "whale" },
      { char: "🦈", name: "shark" },
      { char: "🐊", name: "crocodile" },
      { char: "🐅", name: "tiger" },
      { char: "🐘", name: "elephant" },
      { char: "🦒", name: "giraffe" },
      { char: "🐪", name: "camel" },
      { char: "🐎", name: "horse racing" },
      { char: "🐖", name: "pig" },
      { char: "🌵", name: "cactus plant" },
      { char: "🌲", name: "evergreen tree pine" },
      { char: "🌳", name: "tree" },
      { char: "🌴", name: "palm tree" },
      { char: "🌱", name: "seedling sprout" },
      { char: "🌿", name: "herb leaf" },
      { char: "☘️", name: "shamrock clover" },
      { char: "🍀", name: "four leaf clover luck" },
      { char: "🍁", name: "maple leaf autumn" },
      { char: "🍂", name: "fallen leaves autumn" },
      { char: "🍃", name: "leaf wind" },
      { char: "🌾", name: "sheaf rice grain" },
      { char: "🌷", name: "tulip flower" },
      { char: "🌹", name: "rose flower" },
      { char: "🥀", name: "wilted flower" },
      { char: "🌺", name: "hibiscus flower" },
      { char: "🌸", name: "cherry blossom flower" },
      { char: "🌼", name: "blossom flower" },
      { char: "🌻", name: "sunflower" },
      { char: "🌞", name: "sun face" },
      { char: "🌝", name: "full moon face" },
      { char: "🌛", name: "moon face" },
      { char: "🌙", name: "crescent moon night" },
      { char: "⭐", name: "star" },
      { char: "🌟", name: "glowing star" },
      { char: "🌈", name: "rainbow" },
      { char: "☀️", name: "sun sunny" },
      { char: "⛅", name: "sun behind cloud" },
      { char: "☁️", name: "cloud" },
      { char: "⛈️", name: "storm thunder" },
      { char: "❄️", name: "snowflake cold" },
      { char: "⛄", name: "snowman" },
      { char: "💧", name: "droplet water" },
      { char: "🌊", name: "wave ocean water" },
    ],
  },
  {
    id: "food",
    label: "Food & drink",
    icon: "🍔",
    emojis: [
      { char: "🍏", name: "green apple" },
      { char: "🍎", name: "red apple" },
      { char: "🍐", name: "pear" },
      { char: "🍊", name: "orange tangerine" },
      { char: "🍋", name: "lemon" },
      { char: "🍌", name: "banana" },
      { char: "🍉", name: "watermelon" },
      { char: "🍇", name: "grapes" },
      { char: "🍓", name: "strawberry" },
      { char: "🫐", name: "blueberries" },
      { char: "🍒", name: "cherries" },
      { char: "🍑", name: "peach" },
      { char: "🥭", name: "mango" },
      { char: "🍍", name: "pineapple" },
      { char: "🥥", name: "coconut" },
      { char: "🥝", name: "kiwi" },
      { char: "🍅", name: "tomato" },
      { char: "🥑", name: "avocado" },
      { char: "🥦", name: "broccoli" },
      { char: "🥕", name: "carrot" },
      { char: "🌽", name: "corn" },
      { char: "🌶️", name: "hot pepper chili spicy" },
      { char: "🥔", name: "potato" },
      { char: "🍠", name: "sweet potato" },
      { char: "🥐", name: "croissant" },
      { char: "🍞", name: "bread" },
      { char: "🥖", name: "baguette bread" },
      { char: "🥨", name: "pretzel" },
      { char: "🧀", name: "cheese" },
      { char: "🥚", name: "egg" },
      { char: "🍳", name: "fried egg cooking" },
      { char: "🥞", name: "pancakes" },
      { char: "🧇", name: "waffle" },
      { char: "🥓", name: "bacon" },
      { char: "🍔", name: "hamburger burger" },
      { char: "🍟", name: "fries chips" },
      { char: "🍕", name: "pizza" },
      { char: "🌭", name: "hot dog" },
      { char: "🥪", name: "sandwich" },
      { char: "🌮", name: "taco" },
      { char: "🌯", name: "burrito" },
      { char: "🥙", name: "pita wrap" },
      { char: "🍜", name: "ramen noodles" },
      { char: "🍝", name: "spaghetti pasta" },
      { char: "🍲", name: "stew pot" },
      { char: "🍛", name: "curry rice" },
      { char: "🍣", name: "sushi" },
      { char: "🍱", name: "bento box" },
      { char: "🍙", name: "rice ball" },
      { char: "🍚", name: "rice" },
      { char: "🍤", name: "shrimp tempura fried" },
      { char: "🍦", name: "soft ice cream" },
      { char: "🍨", name: "ice cream" },
      { char: "🍧", name: "shaved ice" },
      { char: "🍩", name: "donut doughnut" },
      { char: "🍪", name: "cookie" },
      { char: "🎂", name: "birthday cake" },
      { char: "🍰", name: "cake slice shortcake" },
      { char: "🧁", name: "cupcake" },
      { char: "🥧", name: "pie" },
      { char: "🍫", name: "chocolate bar" },
      { char: "🍬", name: "candy sweet" },
      { char: "🍭", name: "lollipop" },
      { char: "🍯", name: "honey" },
      { char: "🍼", name: "baby bottle milk" },
      { char: "🥛", name: "milk glass" },
      { char: "☕", name: "coffee tea hot" },
      { char: "🍵", name: "tea green" },
      { char: "🧃", name: "juice box" },
      { char: "🥤", name: "soda cup drink" },
      { char: "🍺", name: "beer" },
      { char: "🍻", name: "beers cheers" },
      { char: "🥂", name: "champagne cheers toast" },
      { char: "🍷", name: "wine" },
      { char: "🥃", name: "whiskey tumbler" },
      { char: "🍸", name: "cocktail martini" },
      { char: "🍹", name: "tropical drink" },
      { char: "🍾", name: "champagne bottle" },
    ],
  },
  {
    id: "activities",
    label: "Activities",
    icon: "⚽",
    emojis: [
      { char: "⚽", name: "soccer football" },
      { char: "🏀", name: "basketball" },
      { char: "🏈", name: "american football" },
      { char: "⚾", name: "baseball" },
      { char: "🥎", name: "softball" },
      { char: "🎾", name: "tennis" },
      { char: "🏐", name: "volleyball" },
      { char: "🏉", name: "rugby" },
      { char: "🥏", name: "frisbee" },
      { char: "🎱", name: "pool 8 ball billiards" },
      { char: "🏓", name: "ping pong table tennis" },
      { char: "🏸", name: "badminton" },
      { char: "🥅", name: "goal net" },
      { char: "🏒", name: "hockey" },
      { char: "🏑", name: "field hockey" },
      { char: "🥍", name: "lacrosse" },
      { char: "🏏", name: "cricket" },
      { char: "⛳", name: "golf flag" },
      { char: "🏹", name: "bow arrow archery" },
      { char: "🎣", name: "fishing" },
      { char: "🥊", name: "boxing glove" },
      { char: "🥋", name: "martial arts karate" },
      { char: "⛸️", name: "ice skate" },
      { char: "🛹", name: "skateboard" },
      { char: "🛷", name: "sled" },
      { char: "🎿", name: "skis" },
      { char: "⛷️", name: "skier" },
      { char: "🏂", name: "snowboard" },
      { char: "🏋️", name: "weightlifting gym" },
      { char: "🤸", name: "cartwheel gymnastics" },
      { char: "🤼", name: "wrestling" },
      { char: "🤽", name: "water polo" },
      { char: "🤾", name: "handball" },
      { char: "🏇", name: "horse racing" },
      { char: "🧘", name: "yoga meditation" },
      { char: "🏄", name: "surfing" },
      { char: "🏊", name: "swimming" },
      { char: "🚣", name: "rowing boat" },
      { char: "🚴", name: "cycling bike" },
      { char: "🚵", name: "mountain biking" },
      { char: "🏆", name: "trophy win champion" },
      { char: "🥇", name: "gold medal first" },
      { char: "🥈", name: "silver medal second" },
      { char: "🥉", name: "bronze medal third" },
      { char: "🏅", name: "medal" },
      { char: "🎖️", name: "military medal" },
      { char: "🎗️", name: "reminder ribbon" },
      { char: "🎯", name: "dart bullseye target" },
      { char: "🎮", name: "video game controller" },
      { char: "🕹️", name: "joystick game" },
      { char: "🎲", name: "dice game" },
      { char: "🎰", name: "slot machine" },
      { char: "🎳", name: "bowling" },
      { char: "🎨", name: "art palette paint" },
      { char: "🎭", name: "theater masks drama" },
      { char: "🎪", name: "circus tent" },
      { char: "🎬", name: "clapper film movie" },
      { char: "🎤", name: "microphone sing karaoke" },
      { char: "🎧", name: "headphones music" },
      { char: "🎼", name: "musical score" },
      { char: "🎵", name: "music note" },
      { char: "🎶", name: "music notes" },
      { char: "🎹", name: "piano keyboard" },
      { char: "🥁", name: "drum" },
      { char: "🎷", name: "saxophone" },
      { char: "🎺", name: "trumpet" },
      { char: "🎸", name: "guitar" },
      { char: "🎻", name: "violin" },
    ],
  },
  {
    id: "travel",
    label: "Travel & places",
    icon: "🚗",
    emojis: [
      { char: "🚗", name: "car automobile" },
      { char: "🚕", name: "taxi" },
      { char: "🚙", name: "suv car" },
      { char: "🚌", name: "bus" },
      { char: "🚎", name: "trolleybus" },
      { char: "🏎️", name: "race car" },
      { char: "🚓", name: "police car" },
      { char: "🚑", name: "ambulance" },
      { char: "🚒", name: "fire truck" },
      { char: "🚐", name: "minibus van" },
      { char: "🚚", name: "delivery truck" },
      { char: "🚛", name: "truck lorry" },
      { char: "🚜", name: "tractor" },
      { char: "🏍️", name: "motorcycle" },
      { char: "🛵", name: "scooter" },
      { char: "🚲", name: "bicycle bike" },
      { char: "🛴", name: "kick scooter" },
      { char: "🚂", name: "train locomotive" },
      { char: "🚆", name: "train" },
      { char: "🚄", name: "high speed train bullet" },
      { char: "🚝", name: "monorail" },
      { char: "🚊", name: "tram" },
      { char: "🚉", name: "station" },
      { char: "✈️", name: "airplane plane flight" },
      { char: "🛫", name: "airplane departure" },
      { char: "🛬", name: "airplane arrival" },
      { char: "🚁", name: "helicopter" },
      { char: "🚀", name: "rocket launch space" },
      { char: "🛸", name: "ufo flying saucer" },
      { char: "⛵", name: "sailboat" },
      { char: "🚤", name: "speedboat" },
      { char: "🛥️", name: "motor boat" },
      { char: "🚢", name: "ship" },
      { char: "⚓", name: "anchor" },
      { char: "⛽", name: "fuel gas station" },
      { char: "🚦", name: "traffic light" },
      { char: "🚧", name: "construction barrier" },
      { char: "🗺️", name: "world map" },
      { char: "🗿", name: "moai statue" },
      { char: "🗽", name: "statue of liberty" },
      { char: "🗼", name: "tokyo tower" },
      { char: "🏰", name: "castle" },
      { char: "🏯", name: "japanese castle" },
      { char: "🏟️", name: "stadium" },
      { char: "🎡", name: "ferris wheel" },
      { char: "🎢", name: "roller coaster" },
      { char: "🎠", name: "carousel" },
      { char: "⛲", name: "fountain" },
      { char: "⛱️", name: "beach umbrella" },
      { char: "🏖️", name: "beach" },
      { char: "🏝️", name: "desert island" },
      { char: "⛰️", name: "mountain" },
      { char: "🏔️", name: "snow mountain" },
      { char: "🌋", name: "volcano" },
      { char: "🏕️", name: "camping tent" },
      { char: "🏠", name: "house home" },
      { char: "🏡", name: "house garden home" },
      { char: "🏢", name: "office building" },
      { char: "🏬", name: "department store" },
      { char: "🏭", name: "factory" },
      { char: "🏥", name: "hospital" },
      { char: "🏦", name: "bank" },
      { char: "🏨", name: "hotel" },
      { char: "🏫", name: "school" },
      { char: "⛪", name: "church" },
      { char: "🕌", name: "mosque" },
      { char: "🛕", name: "temple" },
      { char: "🌆", name: "cityscape dusk" },
      { char: "🌃", name: "night city stars" },
      { char: "🌉", name: "bridge night" },
      { char: "🌁", name: "foggy" },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "💡",
    emojis: [
      { char: "⌚", name: "watch time" },
      { char: "📱", name: "phone mobile smartphone" },
      { char: "💻", name: "laptop computer" },
      { char: "⌨️", name: "keyboard" },
      { char: "🖥️", name: "desktop computer monitor" },
      { char: "🖨️", name: "printer" },
      { char: "🖱️", name: "mouse computer" },
      { char: "💾", name: "floppy disk save" },
      { char: "💿", name: "cd disc" },
      { char: "📀", name: "dvd disc" },
      { char: "📷", name: "camera photo" },
      { char: "📸", name: "camera flash photo" },
      { char: "📹", name: "video camera" },
      { char: "🎥", name: "movie camera film" },
      { char: "📞", name: "telephone call" },
      { char: "☎️", name: "phone landline" },
      { char: "📺", name: "television tv" },
      { char: "📻", name: "radio" },
      { char: "🔋", name: "battery" },
      { char: "🔌", name: "plug electric" },
      { char: "💡", name: "light bulb idea" },
      { char: "🔦", name: "flashlight torch" },
      { char: "🕯️", name: "candle" },
      { char: "🧯", name: "fire extinguisher" },
      { char: "💰", name: "money bag" },
      { char: "💵", name: "dollar money cash" },
      { char: "💳", name: "credit card" },
      { char: "💎", name: "gem diamond jewel" },
      { char: "⚖️", name: "balance scale justice" },
      { char: "🔧", name: "wrench tool" },
      { char: "🔨", name: "hammer tool" },
      { char: "🛠️", name: "hammer wrench tools" },
      { char: "⚙️", name: "gear settings" },
      { char: "🔩", name: "nut bolt" },
      { char: "🧲", name: "magnet" },
      { char: "🔫", name: "water gun" },
      { char: "💣", name: "bomb" },
      { char: "🧨", name: "firecracker dynamite" },
      { char: "🔪", name: "knife" },
      { char: "🗡️", name: "dagger sword" },
      { char: "🛡️", name: "shield" },
      { char: "🚬", name: "cigarette smoking" },
      { char: "🔮", name: "crystal ball fortune" },
      { char: "🧿", name: "nazar amulet" },
      { char: "💊", name: "pill medicine" },
      { char: "💉", name: "syringe shot" },
      { char: "🩹", name: "bandage" },
      { char: "🩺", name: "stethoscope" },
      { char: "🔑", name: "key" },
      { char: "🗝️", name: "old key" },
      { char: "🚪", name: "door" },
      { char: "🛋️", name: "couch sofa" },
      { char: "🛏️", name: "bed" },
      { char: "🚽", name: "toilet" },
      { char: "🚿", name: "shower" },
      { char: "🛁", name: "bathtub bath" },
      { char: "🧻", name: "toilet paper" },
      { char: "🧴", name: "lotion soap bottle" },
      { char: "🧼", name: "soap" },
      { char: "🪥", name: "toothbrush" },
      { char: "🎁", name: "gift present" },
      { char: "🎈", name: "balloon party" },
      { char: "🎀", name: "ribbon bow" },
      { char: "📚", name: "books" },
      { char: "📖", name: "open book reading" },
      { char: "📝", name: "memo note writing" },
      { char: "✏️", name: "pencil" },
      { char: "🖊️", name: "pen" },
      { char: "📌", name: "pushpin pin" },
      { char: "📎", name: "paperclip" },
      { char: "✂️", name: "scissors cut" },
      { char: "📅", name: "calendar date" },
      { char: "📆", name: "calendar" },
      { char: "📈", name: "chart up trending" },
      { char: "📉", name: "chart down" },
      { char: "📊", name: "bar chart" },
      { char: "🔒", name: "lock locked secure" },
      { char: "🔓", name: "unlock open" },
      { char: "🔔", name: "bell notification" },
      { char: "🔕", name: "bell off mute" },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "❤️",
    emojis: [
      { char: "✅", name: "check mark done yes" },
      { char: "❌", name: "cross mark no wrong" },
      { char: "❎", name: "cross mark button" },
      { char: "➕", name: "plus add" },
      { char: "➖", name: "minus subtract" },
      { char: "➗", name: "divide" },
      { char: "✖️", name: "multiply times" },
      { char: "♾️", name: "infinity" },
      { char: "❓", name: "question mark" },
      { char: "❔", name: "white question mark" },
      { char: "❗", name: "exclamation" },
      { char: "❕", name: "white exclamation" },
      { char: "‼️", name: "double exclamation" },
      { char: "⁉️", name: "exclamation question" },
      { char: "💲", name: "dollar sign money" },
      { char: "💱", name: "currency exchange" },
      { char: "™️", name: "trademark" },
      { char: "©️", name: "copyright" },
      { char: "®️", name: "registered" },
      { char: "〰️", name: "wavy dash" },
      { char: "➰", name: "curly loop" },
      { char: "🔚", name: "end arrow" },
      { char: "🔙", name: "back arrow" },
      { char: "🔛", name: "on arrow" },
      { char: "🔝", name: "top up arrow" },
      { char: "🔜", name: "soon arrow" },
      { char: "✔️", name: "check mark" },
      { char: "☑️", name: "checkbox checked" },
      { char: "🔘", name: "radio button" },
      { char: "⚪", name: "white circle" },
      { char: "⚫", name: "black circle" },
      { char: "🔴", name: "red circle" },
      { char: "🟠", name: "orange circle" },
      { char: "🟡", name: "yellow circle" },
      { char: "🟢", name: "green circle" },
      { char: "🔵", name: "blue circle" },
      { char: "🟣", name: "purple circle" },
      { char: "🟤", name: "brown circle" },
      { char: "🔺", name: "red triangle up" },
      { char: "🔻", name: "red triangle down" },
      { char: "🔸", name: "small orange diamond" },
      { char: "🔹", name: "small blue diamond" },
      { char: "🔶", name: "large orange diamond" },
      { char: "🔷", name: "large blue diamond" },
      { char: "⭐", name: "star" },
      { char: "🌟", name: "glowing star" },
      { char: "⚡", name: "lightning bolt zap" },
      { char: "☄️", name: "comet" },
      { char: "💥", name: "boom" },
      { char: "🔥", name: "fire" },
      { char: "🌈", name: "rainbow" },
      { char: "☮️", name: "peace" },
      { char: "☯️", name: "yin yang" },
      { char: "✝️", name: "cross christian" },
      { char: "☪️", name: "star crescent islam" },
      { char: "🕉️", name: "om hindu" },
      { char: "✡️", name: "star of david" },
      { char: "🔯", name: "six pointed star" },
      { char: "♈", name: "aries zodiac" },
      { char: "♉", name: "taurus zodiac" },
      { char: "♊", name: "gemini zodiac" },
      { char: "♋", name: "cancer zodiac" },
      { char: "♌", name: "leo zodiac" },
      { char: "♍", name: "virgo zodiac" },
      { char: "♎", name: "libra zodiac" },
      { char: "♏", name: "scorpio zodiac" },
      { char: "♐", name: "sagittarius zodiac" },
      { char: "♑", name: "capricorn zodiac" },
      { char: "♒", name: "aquarius zodiac" },
      { char: "♓", name: "pisces zodiac" },
      { char: "⛎", name: "ophiuchus zodiac" },
      { char: "🆔", name: "id" },
      { char: "🉑", name: "acceptable" },
      { char: "🆚", name: "vs versus" },
      { char: "🆕", name: "new" },
      { char: "🆓", name: "free" },
      { char: "🆒", name: "cool" },
      { char: "🆗", name: "ok" },
      { char: "🆖", name: "ng no good" },
      { char: "🈁", name: "here" },
      { char: "🅰️", name: "a button blood" },
      { char: "🅱️", name: "b button blood" },
      { char: "🅾️", name: "o button blood" },
      { char: "🆎", name: "ab button blood" },
      { char: "💠", name: "diamond dot" },
      { char: "🚸", name: "children crossing" },
      { char: "⚠️", name: "warning caution" },
      { char: "🚫", name: "prohibited no entry" },
      { char: "♻️", name: "recycle" },
    ],
  },
  {
    id: "flags",
    label: "Flags",
    icon: "🚩",
    emojis: [
      { char: "🏁", name: "checkered flag finish race" },
      { char: "🚩", name: "triangular flag" },
      { char: "🎌", name: "crossed flags japan" },
      { char: "🏴", name: "black flag" },
      { char: "🏳️", name: "white flag" },
      { char: "🏳️‍🌈", name: "rainbow flag pride" },
      { char: "🏴‍☠️", name: "pirate flag" },
      { char: "🇺🇸", name: "united states usa flag" },
      { char: "🇬🇧", name: "united kingdom uk britain flag" },
      { char: "🇨🇦", name: "canada flag" },
      { char: "🇦🇺", name: "australia flag" },
      { char: "🇩🇪", name: "germany flag" },
      { char: "🇫🇷", name: "france flag" },
      { char: "🇮🇹", name: "italy flag" },
      { char: "🇪🇸", name: "spain flag" },
      { char: "🇵🇹", name: "portugal flag" },
      { char: "🇳🇱", name: "netherlands flag" },
      { char: "🇧🇷", name: "brazil flag" },
      { char: "🇲🇽", name: "mexico flag" },
      { char: "🇯🇵", name: "japan flag" },
      { char: "🇰🇷", name: "south korea flag" },
      { char: "🇨🇳", name: "china flag" },
      { char: "🇮🇳", name: "india flag" },
      { char: "🇷🇺", name: "russia flag" },
      { char: "🇸🇬", name: "singapore flag" },
      { char: "🇭🇰", name: "hong kong flag" },
      { char: "🇹🇼", name: "taiwan flag" },
      { char: "🇹🇭", name: "thailand flag" },
      { char: "🇮🇩", name: "indonesia flag" },
      { char: "🇵🇭", name: "philippines flag" },
      { char: "🇻🇳", name: "vietnam flag" },
      { char: "🇲🇾", name: "malaysia flag" },
      { char: "🇸🇪", name: "sweden flag" },
      { char: "🇳🇴", name: "norway flag" },
      { char: "🇩🇰", name: "denmark flag" },
      { char: "🇫🇮", name: "finland flag" },
      { char: "🇵🇱", name: "poland flag" },
      { char: "🇨🇭", name: "switzerland flag" },
      { char: "🇦🇹", name: "austria flag" },
      { char: "🇧🇪", name: "belgium flag" },
      { char: "🇮🇪", name: "ireland flag" },
      { char: "🇬🇷", name: "greece flag" },
      { char: "🇹🇷", name: "turkey flag" },
      { char: "🇿🇦", name: "south africa flag" },
      { char: "🇦🇷", name: "argentina flag" },
      { char: "🇨🇱", name: "chile flag" },
      { char: "🇳🇿", name: "new zealand flag" },
    ],
  },
];
